# Generated by Django 6.0.2 on 2026-02-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=20, unique=True)),
                ('roll_no', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('father_mobile', models.CharField(blank=True, max_length=15)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField()),
                ('attempt1_time', models.DateTimeField(blank=True, null=True)),
                ('attempt2_time', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(blank=True, choices=[('received', 'Received'), ('not_received', 'Not Received')], max_length=20, null=True)),
                ('talked_with', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('parent_reason', models.TextField(blank=True)),
                ('message_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('student', 'week_no')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField()),
                ('total_lectures', models.IntegerField()),
                ('attended_lectures', models.IntegerField()),
                ('week_percentage', models.FloatField()),
                ('overall_percentage', models.FloatField()),
                ('call_required', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('week_no', 'student')},
            },
        ),
    ]
