# Generated by Django 6.0.2 on 2026-02-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended_lectures',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_lectures',
        ),
    ]
