# Generated by Django 6.0.2 on 2026-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_attendance_attended_lectures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(unique=True)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
    ]
