# Generated by Django 6.0.2 on 2026-02-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_weeklock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='core.mentor')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='core_mentor_token_508590_idx'), models.Index(fields=['mentor', 'is_active'], name='core_mentor_mentor__0cfcfb_idx')],
            },
        ),
    ]
