# Generated by Django 6.0.2 on 2026-02-23 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mentorauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResultUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('REMEDIAL', 'REMEDIAL')], max_length=20)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_matched', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='core.subject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('test_name', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ResultCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1_time', models.DateTimeField(blank=True, null=True)),
                ('attempt2_time', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(blank=True, choices=[('received', 'Received'), ('not_received', 'Not Received')], max_length=20, null=True)),
                ('talked_with', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('parent_reason', models.TextField(blank=True)),
                ('message_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fail_reason', models.CharField(blank=True, max_length=255)),
                ('marks_current', models.FloatField(default=0)),
                ('marks_total', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.resultupload')),
            ],
            options={
                'ordering': ['student__roll_no', 'student__name'],
                'unique_together': {('upload', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=20)),
                ('marks_current', models.FloatField(default=0)),
                ('marks_t1', models.FloatField(blank=True, null=True)),
                ('marks_t2', models.FloatField(blank=True, null=True)),
                ('marks_t3', models.FloatField(blank=True, null=True)),
                ('marks_t4', models.FloatField(blank=True, null=True)),
                ('marks_total', models.FloatField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('fail_flag', models.BooleanField(default=False)),
                ('fail_reason', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.resultupload')),
            ],
            options={
                'unique_together': {('upload', 'student')},
            },
        ),
    ]
