# Generated by Django 6.0.2 on 2026-02-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_resultupload_resultcallrecord_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_called_target', models.CharField(blank=True, choices=[('student', 'Student'), ('father', 'Father')], max_length=20)),
                ('attempt1_time', models.DateTimeField(blank=True, null=True)),
                ('attempt2_time', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(blank=True, choices=[('received', 'Received'), ('not_received', 'Not Received')], max_length=20, null=True)),
                ('talked_with', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('student', 'Student')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('parent_remark', models.TextField(blank=True)),
                ('call_done_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_calls', to='core.mentor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_call', to='core.student')),
            ],
            options={
                'ordering': ['student__roll_no', 'student__name'],
            },
        ),
    ]
