# Generated by Django 6.0.2 on 2026-02-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_othercallrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
