# Generated by Django 6.0.2 on 2026-02-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
