# Generated by Django 6.0.2 on 2026-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subject_result_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='marks_current',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
