# Generated by Django 6.0.2 on 2026-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_academic_module_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercallrecord',
            name='call_category',
            field=models.CharField(choices=[('less_attendance', 'Less Attendance'), ('poor_result', 'Poor Result'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='othercallrecord',
            name='exam_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='othercallrecord',
            name='marks_obtained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercallrecord',
            name='marks_out_of',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercallrecord',
            name='subject_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
