# Generated by Django 6.0.2 on 2026-02-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_othercallrecord_call_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('current_enrollment', models.CharField(blank=True, max_length=32)),
                ('current_student_name', models.CharField(blank=True, max_length=150)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_upload_jobs', to='core.academicmodule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
