# Generated by Django 6.0.2 on 2026-02-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_resultuploadjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_practical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_theory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PracticalMarkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_matched', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_mark_uploads', to='core.academicmodule')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SifMarksLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('locked_by', models.CharField(blank=True, max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sif_marks_lock', to='core.academicmodule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPracticalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_marks', models.FloatField(blank=True, null=True)),
                ('attendance_percentage', models.FloatField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_practical_marks', to='core.academicmodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_marks', to='core.subject')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.practicalmarkupload')),
            ],
            options={
                'ordering': ['student__roll_no', 'student__name', 'subject__name'],
                'unique_together': {('module', 'student', 'subject')},
            },
        ),
    ]
