# Generated by Django 6.0.2 on 2026-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_subject_has_practical_subject_has_theory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
