# Generated by Codex on 2026-02-25

from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_superadmins(apps, schema_editor):
    User = apps.get_model("auth", "User")

    creds = [
        ("superadmin1", "super@LJ111"),
        ("superadmin2", "super@LJ222"),
    ]

    for username, password in creds:
        user, _ = User.objects.get_or_create(
            username=username,
            defaults={"is_staff": True, "is_superuser": True, "is_active": True},
        )
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.password = make_password(password)
        user.save(update_fields=["is_staff", "is_superuser", "is_active", "password"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_coordinatormoduleaccess"),
    ]

    operations = [
        migrations.RunPython(seed_superadmins, reverse_code=noop_reverse),
    ]
