# Generated by Django 6.0.2 on 2026-03-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mentorpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('has_theory', models.BooleanField(default=True)),
                ('has_practical', models.BooleanField(default=True)),
                ('result_format', models.CharField(choices=[('FULL', 'T1/T2/T3/T4'), ('T4_ONLY', 'Only T4')], default='FULL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='othercallrecord',
            name='call_category',
            field=models.CharField(choices=[('less_attendance', 'Less Attendance'), ('poor_result', 'Poor Result'), ('mentor_intro', 'Mentor Intro Call'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_subjects', to='core.subjecttemplate'),
        ),
    ]
