# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations


def normalize_module_names(apps, schema_editor):
    AcademicModule = apps.get_model("core", "AcademicModule")

    modules = AcademicModule.objects.all().order_by("id")
    for module in modules:
        variant = (module.variant or "").strip()
        semester = (module.semester or "").strip()
        batch = (module.academic_batch or "").strip()
        if not variant or not semester or not batch:
            continue

        target_name = f"{variant}_{semester} - Batch {batch}"
        if module.name == target_name:
            continue

        conflict = AcademicModule.objects.filter(name=target_name).exclude(id=module.id).exists()
        if conflict:
            # Keep existing name when target is already taken by another module.
            continue

        module.name = target_name
        module.save(update_fields=["name"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_subjecttemplate_alter_othercallrecord_call_category_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_module_names, noop_reverse),
    ]

