# Generated by Django 6.0.2 on 2026-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_normalize_module_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
