# Generated by Django 6.0.2 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_student_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="othercallrecord",
            name="student",
            field=models.ForeignKey(on_delete=models.CASCADE, related_name="other_calls", to="core.student"),
        ),
    ]
