# Generated by Django 6.0.2 on 2026-03-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_make_attendance_result_calls_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('t1_start', models.DateField(blank=True, null=True)),
                ('t1_end', models.DateField(blank=True, null=True)),
                ('t2_start', models.DateField(blank=True, null=True)),
                ('t2_end', models.DateField(blank=True, null=True)),
                ('t3_start', models.DateField(blank=True, null=True)),
                ('t3_end', models.DateField(blank=True, null=True)),
                ('t4_start', models.DateField(blank=True, null=True)),
                ('t4_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_calendar', to='core.academicmodule')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('lecture_no', models.IntegerField()),
                ('time_slot', models.CharField(blank=True, max_length=60)),
                ('batch', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('faculty', models.CharField(blank=True, max_length=50)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.academicmodule')),
            ],
            options={
                'ordering': ['day_of_week', 'lecture_no', 'batch'],
                'unique_together': {('module', 'day_of_week', 'lecture_no', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.IntegerField()),
                ('lecture_no', models.IntegerField()),
                ('time_slot', models.CharField(blank=True, max_length=60)),
                ('batch', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('faculty', models.CharField(blank=True, max_length=50)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mentor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='core.academicmodule')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timetableentry')),
            ],
            options={
                'ordering': ['-date', 'lecture_no', 'batch'],
                'unique_together': {('module', 'date', 'lecture_no', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='TimetableUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(blank=True, max_length=120)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_uploads', to='core.academicmodule')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_holidays', to='core.academicmodule')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('module', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LectureAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_absences', to='core.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.lecturesession')),
            ],
            options={
                'ordering': ['session_id', 'student__roll_no'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
