# Generated by Django 6.0.2 on 2026-03-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_academiccalendar_timetableentry_lecturesession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWeekMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual Upload'), ('auto', 'Auto from Daily Attendance')], default='manual', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_week_meta', to='core.academicmodule')),
            ],
            options={
                'ordering': ['-week_no'],
                'unique_together': {('module', 'week_no')},
            },
        ),
    ]
