# Generated by Django 6.0.2 on 2026-03-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_attendanceweekmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch', models.CharField(max_length=30)),
                ('lecture_no', models.IntegerField()),
                ('time_slot', models.CharField(blank=True, max_length=60)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('original_faculty', models.CharField(blank=True, max_length=50)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to='core.mentor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_adjustments', to='core.academicmodule')),
                ('proxy_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_adjustments', to='core.mentor')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timetableentry')),
            ],
            options={
                'ordering': ['-date', 'lecture_no', 'batch'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.academicmodule')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('module', 'name')},
            },
        ),
    ]
