# Generated by Django 6.0.2 on 2026-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_lectureadjustment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureadjustment',
            name='merge_room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
