# Generated by Django 6.0.2 on 2026-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_lectureadjustment_merge_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableupload',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
