# Generated by Django 6.0.2 on 2026-03-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_timetableupload_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.timetableupload'),
        ),
        migrations.AddField(
            model_name='timetableupload',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('module', 'day_of_week', 'lecture_no', 'batch', 'upload')},
        ),
    ]
