# Generated by Django 6.0.2 on 2026-03-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_subject_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subjectalias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MentorModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='core.mentor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_module_accesses', to='core.academicmodule')),
            ],
            options={
                'ordering': ['mentor__name', 'module__name'],
                'unique_together': {('mentor', 'module')},
            },
        ),
        migrations.CreateModel(
            name='MentorAdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accesses', to='core.mentor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_admins', to='core.academicmodule')),
            ],
            options={
                'ordering': ['mentor__name', 'module__name'],
                'unique_together': {('mentor', 'module')},
            },
        ),
    ]
