# Generated by Django 6.0.2 on 2026-03-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_mentor_is_admin_alter_subjectalias_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_group', models.CharField(blank=True, max_length=40)),
                ('change_type', models.CharField(choices=[('proxy', 'Proxy'), ('swap', 'Swap')], max_length=20)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('lecture_no', models.IntegerField()),
                ('batch', models.CharField(max_length=30)),
                ('prev_subject', models.CharField(blank=True, max_length=120)),
                ('prev_faculty', models.CharField(blank=True, max_length=50)),
                ('prev_room', models.CharField(blank=True, max_length=50)),
                ('prev_time_slot', models.CharField(blank=True, max_length=60)),
                ('new_subject', models.CharField(blank=True, max_length=120)),
                ('new_faculty', models.CharField(blank=True, max_length=50)),
                ('new_room', models.CharField(blank=True, max_length=50)),
                ('new_time_slot', models.CharField(blank=True, max_length=60)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_undone', models.BooleanField(default=False)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('undone_by', models.CharField(blank=True, max_length=120)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_changes', to='core.academicmodule')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timetableentry')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
