# Generated by Django 6.0.2 on 2026-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_timetablechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mentor',
            name='faculty_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
