# Generated by Django 6.0.2 on 2026-03-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_mentor_date_of_joining_mentor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
