# Generated by Django 6.0.2 on 2026-03-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_mentor_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorModuleOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_optouts', to='core.mentor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_optouts', to='core.academicmodule')),
            ],
            options={
                'ordering': ['mentor__name', 'module__name'],
                'unique_together': {('mentor', 'module')},
            },
        ),
    ]
