# Generated by Django 6.0.2 on 2026-03-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_mentormoduleoptout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('proxy', 'Proxy'), ('swap', 'Swap'), ('room', 'Room Change')], default='proxy', max_length=20),
        ),
    ]
