# Generated by Django 6.0.2 on 2026-03-18 04:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_lectureadjustment_adjustment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorHomeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('auto', 'Auto (time based)'), ('manual', 'Manual')], default='auto', max_length=12)),
                ('cutoff_time', models.TimeField(default=datetime.time(12, 35))),
                ('before_page', models.CharField(choices=[('/mentor-schedule/', 'My Schedule'), ('/mentor-daily-absentees/', 'Daily Absent Calls'), ('/mentor-dashboard/', 'Weekly Calls'), ('/mentor-mark-attendance/', 'Mark Attendance')], default='/mentor-schedule/', max_length=64)),
                ('after_page', models.CharField(choices=[('/mentor-schedule/', 'My Schedule'), ('/mentor-daily-absentees/', 'Daily Absent Calls'), ('/mentor-dashboard/', 'Weekly Calls'), ('/mentor-mark-attendance/', 'Mark Attendance')], default='/mentor-daily-absentees/', max_length=64)),
                ('manual_page', models.CharField(choices=[('/mentor-schedule/', 'My Schedule'), ('/mentor-daily-absentees/', 'Daily Absent Calls'), ('/mentor-dashboard/', 'Weekly Calls'), ('/mentor-mark-attendance/', 'Mark Attendance')], default='/mentor-schedule/', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_home_setting', to='core.academicmodule')),
            ],
            options={
                'ordering': ['module__name'],
            },
        ),
    ]
