# Generated by Django 6.0.2 on 2026-03-19 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_mentorhomesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='core.university')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YearScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('LY', 'LY')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_scopes', to='core.college')),
            ],
            options={
                'ordering': ['college__name', 'year_code'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('erp_owner', 'ERP Owner'), ('university_head', 'University Head'), ('college_head', 'College Head'), ('year_head', 'Year Head'), ('coordinator', 'Coordinator')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.college')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.academicmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.university')),
                ('year_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.yearscope')),
            ],
            options={
                'ordering': ['user__username', 'role', '-id'],
            },
        ),
        migrations.AddField(
            model_name='academicmodule',
            name='year_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='core.yearscope'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='core_university_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='core_college_unique_university_name'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('university', 'code'), condition=models.Q(('code', ''), _negated=True), name='core_college_unique_university_code'),
        ),
        migrations.AddConstraint(
            model_name='yearscope',
            constraint=models.UniqueConstraint(fields=('college', 'year_code'), name='core_yearscope_unique_college_year'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'university'), name='core_roleassignment_unique_user_role_university'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'college'), name='core_roleassignment_unique_user_role_college'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'year_scope'), name='core_roleassignment_unique_user_role_yearscope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'module'), name='core_roleassignment_unique_user_role_module'),
        ),
    ]
