# Generated by Django 6.0.2 on 2026-03-21 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_seed_local_hierarchy_and_backfill_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_faculty_profile', to='core.mentor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['short_code'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('entry_deadline', models.DateTimeField()),
                ('max_marks', models.DecimalField(decimal_places=1, default=25, max_digits=5)),
                ('pass_marks', models.DecimalField(decimal_places=1, default=9, max_digits=5)),
                ('total_pass_marks', models.DecimalField(decimal_places=1, default=9, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_message', models.CharField(blank=True, max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_exam_entries', to=settings.AUTH_USER_MODEL)),
                ('published_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exam_entries', to='core.resultupload')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_entries', to='core.subject')),
            ],
            options={
                'ordering': ['exam_date', 'start_time', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('range', 'Enrollment Range'), ('batch', 'Batch'), ('manual', 'Manual')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('enrollment_start', models.CharField(blank=True, max_length=20)),
                ('enrollment_end', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_blocks', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_blocks', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.examtimetableentry')),
            ],
            options={
                'ordering': ['timetable_entry__exam_date', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('REMEDIAL', 'REMEDIAL')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='core.academicmodule')),
            ],
            options={
                'ordering': ['module__name', 'test_name'],
                'unique_together': {('module', 'test_name')},
            },
        ),
        migrations.AddField(
            model_name='examtimetableentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.moduleexamsession'),
        ),
        migrations.CreateModel(
            name='ExamBlockStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='core.examblock')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_block_links', to='core.student')),
            ],
            options={
                'ordering': ['student__roll_no', 'student__name'],
                'unique_together': {('block', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamMarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(blank=True, max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='core.examblock')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mark_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mark_entries', to='core.student')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='core.examtimetableentry')),
            ],
            options={
                'ordering': ['student__roll_no', 'student__name'],
                'unique_together': {('timetable_entry', 'student', 'block')},
            },
        ),
        migrations.CreateModel(
            name='ModuleExamManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exam_managers', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_managers', to='core.academicmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_exam_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module__name', 'user__username'],
                'unique_together': {('module', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examtimetableentry',
            unique_together={('session', 'subject')},
        ),
    ]
