# Generated by Django 6.0.2 on 2026-03-24 05:55

from django.db import migrations, models
from django.db.models import F


def backfill_exam_timetable_modes(apps, schema_editor):
    ExamTimetableEntry = apps.get_model('core', 'ExamTimetableEntry')
    ExamTimetableEntry.objects.update(
        mode='offline',
        offline_max_marks=F('max_marks'),
        online_max_marks=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_examfacultyprofile_examtimetableentry_examblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarkentry',
            name='offline_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exammarkentry',
            name='online_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exammarkentry',
            name='raw_offline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exammarkentry',
            name='raw_online',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examtimetableentry',
            name='mode',
            field=models.CharField(choices=[('offline', 'Only Offline'), ('online', 'Only Online'), ('both', 'Also Online')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='examtimetableentry',
            name='offline_max_marks',
            field=models.DecimalField(decimal_places=1, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='examtimetableentry',
            name='online_max_marks',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.RunPython(backfill_exam_timetable_modes, migrations.RunPython.noop),
    ]
