# Generated by Django 6.0.2 on 2026-03-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_exammarkentry_offline_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examblock',
            name='block_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examblock',
            name='delivery_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='examblock',
            name='lab',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='examblock',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
