# Generated by Django 6.0.2 on 2026-03-24 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_examblock_block_number_examblock_delivery_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSeatingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10)),
                ('block_number', models.CharField(blank=True, max_length=20)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('lab', models.CharField(blank=True, max_length=50)),
                ('block_type', models.CharField(choices=[('range', 'Enrollment Range'), ('batch', 'Batch'), ('manual', 'Manual')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('enrollment_start', models.CharField(blank=True, max_length=20)),
                ('enrollment_end', models.CharField(blank=True, max_length=20)),
                ('manual_enrollments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_seating_blocks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_blocks', to='core.moduleexamsession')),
            ],
            options={
                'ordering': ['session__test_name', 'name', 'id'],
            },
        ),
    ]
