# Generated by Django 6.0.2 on 2026-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_examseatingblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='examseatingblock',
            name='dept_label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
