# Generated by Django 6.0.2 on 2026-03-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_examseatingblock_dept_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='examseatingblock',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
