# Generated by Django 6.0.2 on 2026-03-27 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_examseatingblock_is_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimetableentry',
            name='mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('both', 'Both')], default='offline', max_length=10),
        ),
        migrations.CreateModel(
            name='ExamSubjectEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exam_subject_evaluators', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_evaluator_links', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_evaluators', to='core.moduleexamsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_evaluators', to='core.subject')),
            ],
            options={
                'ordering': ['session__test_name', 'subject__name', 'evaluator__username'],
                'unique_together': {('session', 'subject', 'evaluator')},
            },
        ),
    ]
